### ISSUE TITLE
Engines section on package.json avoids installing with yarn

### ISSUE THREAD

**Issue by Pablodotnet** [excellenteasy/ios-icons#13]
As is well known, yarn treat this `engines: {}` section different like npm does, for npm is just like advisory, but yarn treat like required, so it causes an error that npm does not, so if you update node version there or delete that section everything will work well with yarn. 👍   This is happening on your android-icons repository too.

**Comment by davidpfahler** [comment]
@Pablodotnet What would we need to update this section to? Which versions would work with yarn?

**Comment by Pablodotnet** [comment]
Probably deleting it if it is not too necessary or update node version to ^1 I think, that's what it recommends when the error Pops up when running yarn install or yarn upgrade

**Comment by davidpfahler** [comment]
@Pablodotnet I wouldn't want to delete it just because yarn is implementing different behavior. If you can test what setting works with yarn, I'd be happy to implement it, but I need to know that it actually works.

**Comment by Pablodotnet** [comment]
That's why I said 'or update node version to >=4 I think', but ok, I'll fork your repos and test them with that node version.
